Wasm compatible
EternisAI/remote-attestation-verifier pull request #1
Opened 2024-08-30 18:26 UTC by asa93

Current implementation cannot be compiled to wasm because it uses std features and also openssl.

This new implemention has dependencies that don rely on std features. Usage of vectors, format, println and other macros has been removed as well.
I used #![no_std] attribute and I made sure that this crate compiles in wasm in its current version.

The code has also been refactored and made more simple. 
I created a full module and structured the crate to be used externally.

2024-09-11 22:42 UTC, PratyushRT requested changes
Overall lots of solid work in here @asa93 the COSE parsing, X.509 extraction, signature verification all looks good. 

Lets address the following aspects, we can also discuss any that might not be clear:

1. The code doesn't verify the certificate chain. It should validate the entire chain up to a trusted root certificate.
2. There's no check for the certificate's validity period: maybe this is something we do in a future version, or if easy lets add it. In the future we might even have to add certificate revocation checks (CRL or OCSP).
3. I think we should validate the extracted PCR against expected values.
4. The `expect()` in many places will panic on errors so we might want to handle it more gracefully.
5. Missing Checks: No verification of the module_id, no nonce checking 

A side note: looks like we are manually extracting public key from the certificate. Using a standard library function would be more robust. Was there nothing suitable in existing libraries?

2024-09-11 22:42 UTC, PratyushRT commented on src/lib.rs
> +    let certifcate_bytes: [u8; 643] = serde_cbor::to_vec(&certificate)
Lets fix this typo in naming, variable name is consistent but just for quality

2024-09-23 22:04 UTC, saberistic approved these changes
- [x] Parsing and Verifying of Attestation doc generated by Nitriding
- [x] Parsing all certificate related materials from the blob
- [x] Verifying x509 certificates with AWS root
- [x] Verifying attestation document signature
- [x] checking nonce
- [x] checking PCRs
- [x] Github actions with build/test and publish upon merging into main

2024-09-24 00:42 UTC, PratyushRT reviewed
Overall looks great, one small change that we can quickly discuss is considering using a custom error type instead of String for error handling. This would provide more structured and type-safe error handling. Something like the following:

```
use thiserror::Error;

#[derive(Error, Debug)]
pub enum VerificationError {
    #[error("Invalid nonce")]
    InvalidNonce,
    #[error("Invalid PCR at index {0}")]
    InvalidPCR(usize),
    #[error("X509 certificate verification failed: {0}")]
    X509CertVerificationFailed(String),
    #[error("Remote attestation signature verification failed: {0}")]
    SignatureVerificationFailed(String),
    // ... other error types ...
}

// Then update function signatures to use this error type
pub fn verify(...) -> Result<(), VerificationError>
```

2024-09-24 03:44 UTC, asa93 commented
great job

2024-09-24 13:30 UTC, saberistic commented
> great job

you did all the work, I was just the janitor

2024-09-24 13:38 UTC, PratyushRT approved these changes

2024-09-24 13:39 UTC, merged